

--- 

#sumo_config_path: "manhattan/data/manhattan.sumocfg"
sumo_config_path: "configs/lust.sumocfg"

seed: 42

use_gui: false

output_dir: 'output/lust-nopot'

vehicle_type_probabilities:
  UnconnectedVehicle: 0.
  ConnectedVehicle: 0.99
  PoTVehicle: 0.
  SilenceAttacker: 0.
  SpamAttacker: 0.01
  ReplayAttacker: 0.
  #SignalJammingAttacker: 0.
  SybilAttacker: 0.


position_manager:
  range_limit: 200 # meters

network_simulator:
  v2v_pdr: 0.95

perception_simulator:
  vision_distance: 80 # meters
  fov: 60 # degrees (of one side)
  target_max_rotation: 60 # degrees (of one side)

vehicle:
  width: 1.84
  length: 4.88
  width_plate: 0.35
  eid_changing_possibility: 0.0001
  pot_verifier_max_unverified_per_vehicle: 20
