

--- 

#sumo_config_path: "manhattan/data/manhattan.sumocfg"
sumo_config_path: "configs/lust.sumocfg"

seed: 42

use_gui: false #true

output_dir: 'output/lust-pot3'

vehicle_type_probabilities:
  UnconnectedVehicle: 0.
  ConnectedVehicle: 0.
  PoTVehicle: 0.99
  SilenceAttacker: 0.
  SpamAttacker: 0.01
  ReplayAttacker: 0.
  #SignalJammingAttacker: 0.
  SybilAttacker: 0.


position_manager:
  range_limit: 200 # meters

network_simulator:
  v2v_pdr: 0.95

perception_simulator:
  vision_distance: 80 # meters
  vision_angle: 60 # degrees (of one side)

vehicle:
  eid_changing_possibility: 0.0001
  pot_verifier_max_unverified_per_vehicle: 20
  PoTProver:
    send_proof_every: 3 # ticks
    max_queued_proofs: 16
